### ISSUE TITLE
tap2junit is not installed any more

### ISSUE THREAD

**Issue by kbucheli** [bleargh45/TAP-Formatter-JUnit#8]
After installing v0.12 with `cpanm` the `tap2junit` script was missing.

**Comment by bleargh45** [comment]
That seems odd... but, let me look into that for you.

**Comment by bleargh45** [comment]
Will have an updated release out to MetaCPAN for you shortly.

**Comment by bleargh45** [comment]
Just uploaded [v0.13 to MetaCPAN](https://metacpan.org/release/GTERMARS/TAP-Formatter-JUnit-0.13), which should address your issue.

Would you mind giving that a try and seeing if that fixes things properly for you?

**Comment by kbucheli** [comment]
I can confirm that it is now installed. Thank you very much for the fast action.
